SECRET_KEY='postgres'
HOST='postgres'
DATABASE='postgres'
USER='postgres'
PASSWORD='postgres'
TOKEN='REPLACEME'
PROVIDER='https://ethshared.bdnodes.net?auth='+TOKEN
PRIVATE_KEY='REPLACEME'
GRAPH='https://ethshared.bdnodes.net/graphql'
